name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
    - cron: '0 23 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Result'
        run: bash ./weather_forecast.sh
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Shanghai Weather Report
          body: file://result.html
          to: guoxu_1989@163.com
          from: GitHub Actions
          content_type: text/html
